name: Super Linter and CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  super-linter:
    name: Run Super Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Super Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_PYTHON_PYLINT: true
          VALIDATE_JUPYTER: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # test:
  #   name: Run Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.11'

  #     - name: Install Dependencies
  #       run: |
  #         pip install -r requirements.txt
  #         pip install pytest

  #     - name: Run Unit Tests
  #       run: pytest tests/